server:
  port: 8001
  servlet:
    context-path: /
#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qinlinhai
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis配置
mybatis:
  type-aliases-package: com.aaa.entity
  mapper-locations: classpath:mapper/*.xml
mvc:
  date-format: yyyy-MM-dd
jackson:
  date-format: yyyy-MM-dd
  time-zone: GMT+8

logging:
  level:
    com:
      qin:
        mapper: debug