server:
  port: 9000
  servlet:
    context-path: /
#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qinlinhai
    type: com.alibaba.druid.pool.DruidDataSource